#!/bin/bash

DIRECTORIO="/home/kris/Descargas"

LOG_FILE="/home/kris/lab2/Archivo_Log.txt"

if [ ! -d "$DIRECTORIO" ]; then
  echo "El directorio no existe: $DIRECTORIO"
  exit 1
fi

if [ ! -e "$LOG_FILE" ]; then
  touch "$LOG_FILE"
fi
