#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Uso: $0 <ejecutable>"
  exit 1
fi

ejecutable="$1"
log_file="monitoring.log"

monitor_process() {
  while ps -p $pid -o %cpu,%mem --no-headers; do
    ps -p $pid -o %cpu,%mem --no-headers >> "$log_file"
    sleep 1
  done
}

$ejecutable &
pid=$!

date "+Inicio: %Y-%m-%d %H:%M:%S" >> "$log_file"

monitor_process &

wait $pid

date "+Fin: %Y-%m-%d %H:%M:%S" >> "$log_file"
